owner: Jrp-best-hosting
repo: status

sites:
  - name: Website
    url: https://jrp.best
  - name: Node 1
    url: https://none.jrp.best
  - name: Node 2
    url: http://ntwo.jrp.best
  - name: Node 3
    url: http://ntre.jrp.best
  - name: API Server
    url: http://api.jrp.best
  - name: ShareX hosting
    url: https://sharex.jrp.best
  - name: File server
    url: https://img.jrp.best

status-website:
  cname: status.jrp.best
  theme: ocean
  logoUrl: https://givinghawk.xyz/uploaded/jrp.best-favicon.png
  name: JrpBest Server Status
  introTitle: JrpBest Server Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
